[package]
name = "batnet"
version = "0.1.0"
authors = ["pinusc <giuseppe.stelluto@gmail.com>"]

[dependencies]
serde = "1.0.8"
serde_json = "1.0"
serde_derive = "1.0"
rustc-serialize = "0.3.24"
crypto-hash = "0.2.1"
